name = "wolfssl"
description = "WolfSSL encryption library and its Ada bindings"
version = "5.8.0"

authors = ["WolfSSL Team <support@wolfssl.com>"]
maintainers = ["Fernando Oleo Blanco <irvise@irvise.xyz>", "Manuel Gomez <mgrojo@gmail.com>"]
maintainers-logins = ["Irvise", "mgrojo"]
licenses = "GPL-2.0-only"
website = "https://www.wolfssl.com/"
project-files = ["wolfssl.gpr"]
tags = ["ssl", "tls", "embedded", "spark"]

[configuration.variables]
STATIC_PSK = {type = "Boolean", default = false}
