name: MSYS2 Build Test

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  msys2:
    if: github.repository_owner == 'wolfssl'
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: msys
          update: true
          install: git gcc autotools base-devel autoconf netcat
      - name: configure wolfSSL
        run: ./autogen.sh && ./configure --disable-sys-ca-certs CFLAGS="-DUSE_CERT_BUFFERS_2048 -DUSE_CERT_BUFFERS_256 -DNO_WRITE_TEMP_FILES"
      - name: build wolfSSL
        run: make
      - name: run tests
        run: make check
      - name: Display log
        if: always()
        run: cat test-suite.log
